spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/polaris}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:12345}

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}

jwt:
  secret: ${JWT_SECRET:NGUYEN-DINH-TUAN-DAT-SWE-030205}

logging:
  level:
    com.cloud.polaris: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.security: DEBUG

polaris:
  task:
    poll-interval: 1s
    worker-concurrency: 4
    recovery-timeout: 2m
    recovery-interval: 10s
    recovery-batch-size: 100